# Push the style fixes directly to the original PR
#
# This setting implies pull_requests: false for origin PRs, and has no effect on
# forked PRs (since we can't push to those).
#
auto: false

# Open Restyle PRs?
pull_requests: true

# Leave comments on the original PR linking to the Restyle PR?
comments: true

statuses:
  differences: true     # Red when style differences are found
  no_differences: true  # Green when no differences are found
  error: true           # Red if we encounter errors restyling

restylers:
  - image: restyled/restyler-fantomas
    command:
      - fantomas
  - image: restyled/restyler-clang-format
    command:
      - clang-format
      - "-i"
    arguments: []
    include:
      - "**/*.c"
      - "**/*.cc"
      - "**/*.h"
      - "**/*.cmake"

  - image: restyled/restyler-google-java-format
    command:
      - google-java-format
      - "--replace"
    arguments: []
    include:
      - "**/*.java"
    interpreters: []

  - image: restyled/restyler-black
    command:
      - black
    arguments: []
    include:
      - "**/*.py"
    interpreters:
      - python

  - image: restyled/restyler-rustfmt
    command:
      - rustfmt
    arguments: []
    include:
      - "**/*.rs"
    interpreters: []

  - image: restyled/restyler-php-cs-fixer
    command:
      - php-cs-fixer
      - fix
    arguments: []
    include:
      - "**/*.php"
    interpreters: []

  - image: restyled/restyler-prettier
    command:
      - prettier
      - "--write"
    arguments: []
    include:
      - "**/*.json"
      - "**/*.js"
      - "**/*.yml"
      - "**/*.yaml"
    interpreters: []
  
  # Missing clojure
  # Missing crystal
  # Missing csharp
  # Missing dart
  # Missing elixir
  # Missing fsharp
  # Missing go
  # Missing julia
  # Missing kotlin
  # Missing nim
  # Missing perl
  # Missing pony
  # Missing scala
  # Missing swift
